package zzvcom.sys.dao.impl;

import java.util.HashMap;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import zzvcom.sys.dao.BasicinfoDAO;
import zzvcom.sys.pojo.Basicinfo;
import zzvcom.sys.pojo.BasicinfoExample;

public class BasicinfoDAOImpl extends SqlMapClientDaoSupport implements BasicinfoDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public BasicinfoDAOImpl() {
        super();
    }
    
    
 
	@SuppressWarnings("unchecked")
	public HashMap selectProjectByExample(BasicinfoExample example)
			throws Exception {
		HashMap map = (HashMap) getSqlMapClientTemplate().queryForMap(
				"basicinfo.abatorgenerated_selectByExample", example, "id",
				"value");
		return map;
	}

	@SuppressWarnings("unchecked")
	public List<Basicinfo> findBasicInfoByType(BasicinfoExample example)
			throws Exception {
		List<Basicinfo> list = (List<Basicinfo>) getSqlMapClientTemplate()
				.queryForList("basicinfo.findBasicInfoByType", example);
		return list;
	}

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public void insert(Basicinfo record) {
        getSqlMapClientTemplate().insert("basicinfo.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public int updateByPrimaryKey(Basicinfo record) {
        int rows = getSqlMapClientTemplate().update("basicinfo.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public int updateByPrimaryKeySelective(Basicinfo record) {
        int rows = getSqlMapClientTemplate().update("basicinfo.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public List selectByExample(BasicinfoExample example) {
        List list = getSqlMapClientTemplate().queryForList("basicinfo.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public Basicinfo selectByPrimaryKey(String id) {
        Basicinfo key = new Basicinfo();
        key.setId(id);
        Basicinfo record = (Basicinfo) getSqlMapClientTemplate().queryForObject("basicinfo.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public int deleteByExample(BasicinfoExample example) {
        int rows = getSqlMapClientTemplate().delete("basicinfo.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public int deleteByPrimaryKey(String id) {
        Basicinfo key = new Basicinfo();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("basicinfo.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public int countByExample(BasicinfoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("basicinfo.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public int updateByExampleSelective(Basicinfo record, BasicinfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("basicinfo.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public int updateByExample(Basicinfo record, BasicinfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("basicinfo.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    private static class UpdateByExampleParms extends BasicinfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, BasicinfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}