package zzvcom.sys.dao.impl;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import zzvcom.sys.dao.DicttypeDAO;
import zzvcom.sys.pojo.Dicttype;
import zzvcom.sys.pojo.DicttypeExample;

public class DicttypeDAOImpl extends SqlMapClientDaoSupport implements DicttypeDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    public DicttypeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    public void insert(Dicttype record) {
        getSqlMapClientTemplate().insert("dicttype.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    public int updateByPrimaryKey(Dicttype record) {
        int rows = getSqlMapClientTemplate().update("dicttype.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    public int updateByPrimaryKeySelective(Dicttype record) {
        int rows = getSqlMapClientTemplate().update("dicttype.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    public List selectByExample(DicttypeExample example) {
        List list = getSqlMapClientTemplate().queryForList("dicttype.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    public Dicttype selectByPrimaryKey(String typecode) {
        Dicttype key = new Dicttype();
        key.setTypecode(typecode);
        Dicttype record = (Dicttype) getSqlMapClientTemplate().queryForObject("dicttype.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    public int deleteByExample(DicttypeExample example) {
        int rows = getSqlMapClientTemplate().delete("dicttype.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    public int deleteByPrimaryKey(String typecode) {
        Dicttype key = new Dicttype();
        key.setTypecode(typecode);
        int rows = getSqlMapClientTemplate().delete("dicttype.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    public int countByExample(DicttypeExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("dicttype.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    public int updateByExampleSelective(Dicttype record, DicttypeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("dicttype.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    public int updateByExample(Dicttype record, DicttypeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("dicttype.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    private static class UpdateByExampleParms extends DicttypeExample {
        private Object record;

        public UpdateByExampleParms(Object record, DicttypeExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}