package zzvcom.sys.dao;

import java.util.HashMap;
import java.util.List;

import zzvcom.sys.pojo.Basicinfo;
import zzvcom.sys.pojo.BasicinfoExample;

public interface BasicinfoDAO {
 
	
	public HashMap selectProjectByExample(BasicinfoExample example)
	throws Exception;
	public List<Basicinfo> findBasicInfoByType(BasicinfoExample example)
	throws Exception;
	
    void insert(Basicinfo record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    int updateByPrimaryKey(Basicinfo record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    int updateByPrimaryKeySelective(Basicinfo record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    List selectByExample(BasicinfoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    Basicinfo selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    int deleteByExample(BasicinfoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    int countByExample(BasicinfoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    int updateByExampleSelective(Basicinfo record, BasicinfoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table basicinfo
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    int updateByExample(Basicinfo record, BasicinfoExample example);
}