package zzvcom.sys.dao;
import java.util.List;

import zzvcom.sys.pojo.Dicttype;
import zzvcom.sys.pojo.DicttypeExample;

public interface DicttypeDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    void insert(Dicttype record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    int updateByPrimaryKey(Dicttype record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    int updateByPrimaryKeySelective(Dicttype record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    List selectByExample(DicttypeExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    Dicttype selectByPrimaryKey(String typecode);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    int deleteByExample(DicttypeExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    int deleteByPrimaryKey(String typecode);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    int countByExample(DicttypeExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    int updateByExampleSelective(Dicttype record, DicttypeExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dicttype
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    int updateByExample(Dicttype record, DicttypeExample example);
}