package zzvcom.sys.dao;

import java.util.List;

import zzvcom.sys.pojo.Dictinfo;
import zzvcom.sys.pojo.DictinfoExample;

public interface DictinfoDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dictinfo
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    void insert(Dictinfo record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dictinfo
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    int updateByPrimaryKey(Dictinfo record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dictinfo
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    int updateByPrimaryKeySelective(Dictinfo record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dictinfo
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    List selectByExample(DictinfoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dictinfo
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    Dictinfo selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dictinfo
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    int deleteByExample(DictinfoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dictinfo
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dictinfo
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    int countByExample(DictinfoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dictinfo
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    int updateByExampleSelective(Dictinfo record, DictinfoExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table dictinfo
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    int updateByExample(Dictinfo record, DictinfoExample example);
}