package zzvcom.sys.pojo;

public class Basicinfo {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column basicinfo.id
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column basicinfo.name
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column basicinfo.value
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    private String value;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column basicinfo.type
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    private String type;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column basicinfo.tag
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    private String tag;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column basicinfo.isalive
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    private String isalive;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column basicinfo.vchar1
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    private String vchar1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column basicinfo.vchar2
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    private String vchar2;
    
    
    private String typecode;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column basicinfo.id
     *
     * @return the value of basicinfo.id
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column basicinfo.id
     *
     * @param id the value for basicinfo.id
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column basicinfo.name
     *
     * @return the value of basicinfo.name
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column basicinfo.name
     *
     * @param name the value for basicinfo.name
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column basicinfo.value
     *
     * @return the value of basicinfo.value
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column basicinfo.value
     *
     * @param value the value for basicinfo.value
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column basicinfo.type
     *
     * @return the value of basicinfo.type
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column basicinfo.type
     *
     * @param type the value for basicinfo.type
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column basicinfo.tag
     *
     * @return the value of basicinfo.tag
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column basicinfo.tag
     *
     * @param tag the value for basicinfo.tag
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column basicinfo.isalive
     *
     * @return the value of basicinfo.isalive
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public String getIsalive() {
        return isalive;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column basicinfo.isalive
     *
     * @param isalive the value for basicinfo.isalive
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public void setIsalive(String isalive) {
        this.isalive = isalive;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column basicinfo.vchar1
     *
     * @return the value of basicinfo.vchar1
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public String getVchar1() {
        return vchar1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column basicinfo.vchar1
     *
     * @param vchar1 the value for basicinfo.vchar1
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public void setVchar1(String vchar1) {
        this.vchar1 = vchar1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column basicinfo.vchar2
     *
     * @return the value of basicinfo.vchar2
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public String getVchar2() {
        return vchar2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column basicinfo.vchar2
     *
     * @param vchar2 the value for basicinfo.vchar2
     *
     * @abatorgenerated Wed Jan 05 13:33:43 CST 2011
     */
    public void setVchar2(String vchar2) {
        this.vchar2 = vchar2;
    }

	public String getTypecode() {
		return typecode;
	}

	public void setTypecode(String typecode) {
		this.typecode = typecode;
	}
    
    
}