package zzvcom.sys.pojo;

public class Dictinfo {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column dictinfo.id
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column dictinfo.dictcode
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    private String dictcode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column dictinfo.typecode
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    private String typecode;
    
    private String typename;
    
    private String isenable;
    private String valuetype;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column dictinfo.info
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    private String info;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column dictinfo.remark
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    private String remark;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column dictinfo.updatetime
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    private String updatetime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column dictinfo.dictsort
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    private Integer dictsort;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column dictinfo.id
     *
     * @return the value of dictinfo.id
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column dictinfo.id
     *
     * @param id the value for dictinfo.id
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column dictinfo.dictcode
     *
     * @return the value of dictinfo.dictcode
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    public String getDictcode() {
        return dictcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column dictinfo.dictcode
     *
     * @param dictcode the value for dictinfo.dictcode
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    public void setDictcode(String dictcode) {
        this.dictcode = dictcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column dictinfo.typecode
     *
     * @return the value of dictinfo.typecode
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    public String getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column dictinfo.typecode
     *
     * @param typecode the value for dictinfo.typecode
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    public void setTypecode(String typecode) {
        this.typecode = typecode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column dictinfo.info
     *
     * @return the value of dictinfo.info
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column dictinfo.info
     *
     * @param info the value for dictinfo.info
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    public void setInfo(String info) {
        if(info != null){
        	info = info.trim();
        }
        this.info = info;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column dictinfo.remark
     *
     * @return the value of dictinfo.remark
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column dictinfo.remark
     *
     * @param remark the value for dictinfo.remark
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column dictinfo.updatetime
     *
     * @return the value of dictinfo.updatetime
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column dictinfo.updatetime
     *
     * @param updatetime the value for dictinfo.updatetime
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column dictinfo.dictsort
     *
     * @return the value of dictinfo.dictsort
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    public Integer getDictsort() {
        return dictsort;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column dictinfo.dictsort
     *
     * @param dictsort the value for dictinfo.dictsort
     *
     * @abatorgenerated Fri Dec 10 16:57:21 CST 2010
     */
    public void setDictsort(Integer dictsort) {
        this.dictsort = dictsort;
    }

	public String getTypename() {
		return typename;
	}

	public void setTypename(String typename) {
		this.typename = typename;
	}

    public String getIsenable()
    {
        return isenable;
    }

    public void setIsenable(String isenable)
    {
        this.isenable = isenable;
    }

	public String getValuetype() {
		return valuetype;
	}

	public void setValuetype(String valuetype) {
		this.valuetype = valuetype;
	}
    
}