package zzvcom.sys.pojo;

public class Dicttype {
    private String codelength;
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column dicttype.typecode
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    private String typecode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column dicttype.typename
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    private String typename;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column dicttype.remark
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    private String remark;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column dicttype.typesort
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    private Integer typesort;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column dicttype.typecode
     *
     * @return the value of dicttype.typecode
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    public String getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column dicttype.typecode
     *
     * @param typecode the value for dicttype.typecode
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    public void setTypecode(String typecode) {
        this.typecode = typecode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column dicttype.typename
     *
     * @return the value of dicttype.typename
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column dicttype.typename
     *
     * @param typename the value for dicttype.typename
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    public void setTypename(String typename) {
        this.typename = typename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column dicttype.remark
     *
     * @return the value of dicttype.remark
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column dicttype.remark
     *
     * @param remark the value for dicttype.remark
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column dicttype.typesort
     *
     * @return the value of dicttype.typesort
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    public Integer getTypesort() {
        return typesort;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column dicttype.typesort
     *
     * @param typesort the value for dicttype.typesort
     *
     * @abatorgenerated Fri Dec 10 13:58:07 CST 2010
     */
    public void setTypesort(Integer typesort) {
        this.typesort = typesort;
    }

    public String getCodelength()
    {
        return codelength;
    }

    public void setCodelength(String codelength)
    {
        this.codelength = codelength;
    }
}